#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
  path: /register
  controller: App\Controller\DefaultController::register
  methods: POST

login_check:
  path:     /login_check
  methods:  [POST]