# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    ropsten.api.url: 'https://api-ropsten.etherscan.io/api'
    ropsten.api.key: 'FKQFUP47GG13YNJ7MHFZP5NWKP2T3Y2WKU'
    ropsten.api.contract: '0xfaCf2DeE4197560D74E26C1158D17152b5384F2e'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Model/User/Entity,Model/Contract/Entity,Migrations,Tests,Kernel.php}'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Infrastructure\Dispatchers\EventDispatcherInterface:
        class: Infrastructure\Dispatchers\Symfony\MessengerEventDispatcher

    Infrastructure\CommandHandling\CommandBusInterface:
        class: Infrastructure\CommandHandling\SymfonyCommandBus
        autowire: true

    Infrastructure\Http\Client\HttpClientInterface:
        class: Infrastructure\Http\Client\Guzzle\HttpClient
        autowire: true

    App\Model\User\Entity\User\UserRepository: ~
    App\Model\Contract\Entity\Contract\ContractRepository: ~
    App\Model\Contract\Entity\NftTx\NftTxRepository: ~

